version: "3.1"

services:
  web:
    build: ./web
    command: gunicorn web.wsgi --user www-data --bind 0.0.0.0:8010 --workers 3
    ports:
      - 80:8010
    env_file:
      - ./.env
    depends_on:
      - nginx

  nginx:
    image: nginx
    volumes:
      ./nginx/nginx.default:/etc/nginx/nginx.conf:ro
    ports:
      - 80:8020
