version: "3.1"

networks:
  converter_net:
    driver: bridge


services:
  web:
    build: ./web
    command: gunicorn web.wsgi --user www-data --bind 0.0.0.0:5000 --workers 3
    env_file:
      - ./.env
    depends_on:
      - nginx
    networks:
      - converter_net

  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.default:/etc/nginx/nginx.conf:ro
    ports:
      - 5002:5001
    networks:
      - converter_net
