version: '3.7'

services:
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    volumes:
      - web-django:/usr/src/app
      - static_volume:/static
    env_file: .env
    environment:
      DEBUG: 'true'
    command: python manage.py runserver
    networks:
      - web_network

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "5000:5000"
    volumes:
      - static_volume:/static
    links:
      - web:web
    networks:
      - web_network

# указываются используемые сети
networks:
  web_network:
    driver: bridge

volumes:
  web-django:
  static_volume:
